# Generated by Django 3.0 on 2019-12-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('killboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='victimlog',
            name='event_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='victimlog',
            unique_together={('timestamp', 'event_id')},
        ),
    ]
